name: Merge Master to Main

on:
  push:
    branches:
      - master

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure Git (needed for merge commit)
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Fetch all branches
      - name: Fetch All Branches
        run: git fetch --all

      # Step 4: Merge master into main
      - name: Merge Master into Main
        run: |
          git checkout main
          git merge master --no-edit

      # Step 5: Push the changes to main
      - name: Push Changes
        run: git push origin main
        
