name: Merge Test to Master

on:
  push:
    branches:
      - test

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Fetch All Branches
      - name: Fetch All Branches
        run: git fetch --all

      # Step 4: Merge Test into Master with Conflict Handling
      - name: Attempt to Merge Test into Master
        run: |
          git checkout master
          git merge test --no-edit || (echo "Merge conflict detected" && git merge --abort && exit 1)

      # Step 5: Push Changes to Master
      - name: Push Changes to Master
        if: success()
        run: git push origin master
