name: Merge Test to Master

on:
  push:
    branches:
      - test  # Trigger workflow on push to test branch

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Configure Git for the Workflow
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Fetch All Branches
      - name: Fetch All Branches
        run: git fetch --all

      # Step 4: Merge Test into Master
      - name: Merge Test into Master
        run: |
          git checkout master   # Ensure you're on the master branch
          git merge test --no-edit  # Merge the test branch into master

      # Step 5: Push Merged Changes to Master
      - name: Push Changes to Master
        run: git push origin master  # Push the merged changes to the master branch
